In [1]:
import numpy as np

# Constants
sound_speed = 340  # m/s (sound speed in air)
lat_conversion = 111263  # meters per degree of latitude
lon_conversion = 97304   # meters per degree of longitude

# Best explosion positions (longitude, latitude, height in meters)
explosion_positions = np.array([
    [110.43229428, 27.69959271, 773.16170389],
    [110.45972478, 27.66572359, 562.5007344],
    [110.44161337, 27.71039823, 457.62733576],
    [110.95189292, 27.59129019, 789.20322411]
])

# Best explosion times in seconds
explosion_times = np.array([28.58986215, 28.59011388, 33.58986214, 33.58890358])

# Convert explosion positions (longitude, latitude) to meters (local approximation)
explosion_positions_m = explosion_positions.copy()
explosion_positions_m[:, 0] *= lon_conversion  # Convert longitude to meters
explosion_positions_m[:, 1] *= lat_conversion  # Convert latitude to meters

# Simulate 7 devices with random positions (longitude, latitude, height in meters)
np.random.seed(42)  # For reproducibility
device_longitudes = np.random.uniform(110.4, 110.95, 7)  # Random longitudes (degrees)
device_latitudes = np.random.uniform(27.55, 27.72, 7)    # Random latitudes (degrees)
device_heights = np.random.uniform(400, 800, 7)         # Random heights (meters)

# Create device positions (longitude, latitude, height)
device_positions = np.vstack([device_longitudes, device_latitudes, device_heights]).T

# Convert device positions (longitude, latitude) to meters
device_positions_m = device_positions.copy()
device_positions_m[:, 0] *= lon_conversion  # Convert longitude to meters
device_positions_m[:, 1] *= lat_conversion  # Convert latitude to meters

# Calculate the predicted sound arrival times for each device and explosion
def calculate_arrival_times(device_positions_m, explosion_positions_m, explosion_times):
    arrival_times = []
    for device_position in device_positions_m:
        times = []
        for i in range(len(explosion_positions_m)):
            # Calculate the distance between the device and the explosion in meters
            distance = np.linalg.norm(device_position - explosion_positions_m[i])
            # Calculate the time delay (distance / speed of sound)
            time_delay = distance / sound_speed
            # Calculate the sound arrival time at the device
            arrival_time = explosion_times[i] + time_delay
            times.append(arrival_time)
        arrival_times.append(times)
    return np.array(arrival_times)

# Calculate the sound arrival times at each device
arrival_times = calculate_arrival_times(device_positions_m, explosion_positions_m, explosion_times)

# Output the simulated device positions and arrival times
print("Simulated device positions (longitude, latitude, height in degrees and meters):")
print(device_positions)

print("\nSimulated sound arrival times (t1, t2, t3, t4 in seconds):")
print(arrival_times)


Simulated device positions (longitude, latitude, height in degrees and meters):
[[110.60599707  27.69724994 472.72998688]
 [110.92289287  27.65218955 473.36180394]
 [110.80259667  27.67037234 521.69689718]
 [110.72926217  27.55349936 609.90257265]
 [110.48581025  27.71488467 572.77800746]
 [110.48579699  27.69151525 516.49165608]
 [110.43194599  27.58609765 644.74115789]]

Simulated sound arrival times (t1, t2, t3, t4 in seconds):
[[ 78.31531873  71.7048884   80.83091504 138.48162943]
 [169.85049875 161.21760113 172.6373263   55.19694761]
 [134.99914173 126.72787951 137.726237    83.54821136]
 [126.10363117 114.02465931 130.61198931  98.49444126]
 [ 44.7130846   46.32555176  46.32791491 172.97484727]
 [ 44.14651779  39.85641837  47.66487642 170.95542472]
 [ 65.73250758  55.83408533  74.36419235 182.40190716]]


In [2]:
import numpy as np

# Constants
sound_speed = 340  # m/s (sound speed in air)
lat_conversion = 111263  # meters per degree of latitude
lon_conversion = 97304   # meters per degree of longitude

# Best explosion positions (longitude, latitude, height in meters)
explosion_positions = np.array([
    [110.24881132, 27.71875567, 830.17912749],
    [110.34201478, 27.76222241, 782.72874308],
    [110.41989654, 27.70311125, 495.09025456],
    [110.51613294, 27.9112601, 797.64233002]
])

# Best explosion times in seconds
explosion_times = np.array([11.97872243, 16.97330964, 16.38970079, 16.7949202])

# Convert explosion positions (longitude, latitude) to meters (local approximation)
explosion_positions_m = explosion_positions.copy()
explosion_positions_m[:, 0] *= lon_conversion  # Convert longitude to meters
explosion_positions_m[:, 1] *= lat_conversion  # Convert latitude to meters

# Simulate 7 devices with random positions (longitude, latitude, height in meters)
np.random.seed(42)  # For reproducibility
device_longitudes = np.random.uniform(110.2, 110.6, 7)  # Random longitudes (degrees)
device_latitudes = np.random.uniform(27.65, 27.95, 7)   # Random latitudes (degrees)
device_heights = np.random.uniform(400, 850, 7)         # Random heights (meters)

# Create device positions (longitude, latitude, height)
device_positions = np.vstack([device_longitudes, device_latitudes, device_heights]).T

# Convert device positions (longitude, latitude) to meters
device_positions_m = device_positions.copy()
device_positions_m[:, 0] *= lon_conversion  # Convert longitude to meters
device_positions_m[:, 1] *= lat_conversion  # Convert latitude to meters

# Calculate the predicted sound arrival times for each device and explosion
def calculate_arrival_times(device_positions_m, explosion_positions_m, explosion_times):
    arrival_times = []
    for device_position in device_positions_m:
        times = []
        for i in range(len(explosion_positions_m)):
            # Calculate the distance between the device and the explosion in meters
            distance = np.linalg.norm(device_position - explosion_positions_m[i])
            # Calculate the time delay (distance / speed of sound)
            time_delay = distance / sound_speed
            # Calculate the sound arrival time at the device
            arrival_time = explosion_times[i] + time_delay
            times.append(arrival_time)
        arrival_times.append(times)
    return np.array(arrival_times)

# Calculate the sound arrival times at each device
arrival_times = calculate_arrival_times(device_positions_m, explosion_positions_m, explosion_times)

# Output the simulated device positions and arrival times
print("Simulated device positions (longitude, latitude, height in degrees and meters):")
print(device_positions)

print("\nSimulated sound arrival times (t1, t2, t3, t4 in seconds):")
print(arrival_times)


Simulated device positions (longitude, latitude, height in degrees and meters):
[[110.34981605  27.90985284 481.82123524]
 [110.58028572  27.8303345  482.53202943]
 [110.49279758  27.86242177 536.90900933]
 [110.43946339  27.65617535 636.14039423]
 [110.26240746  27.94097296 594.37525839]
 [110.26239781  27.89973279 531.05311309]
 [110.22323344  27.71370173 675.33380263]]

Simulated sound arrival times (t1, t2, t3, t4 in seconds):
[[ 80.87942777  65.34415916  86.95490613  64.40414831]
 [113.6324238   88.71948867  78.35953699  49.03246073]
 [ 96.16137713  71.17480207  72.54299168  34.13314217]
 [ 70.26053981  61.49611219  32.74341815 103.10683488]
 [ 84.80535102  79.75093274 106.33642441  90.05872399]
 [ 71.33644582  67.41809103  94.95022021  89.51307107]
 [ 19.49712496  54.49388892  72.78145737 122.65452571]]
